<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped Keyed and DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/{Keyed,DefInjected}/**/*.xml key. For each key, resolves the
  English text: a matching Mod/Languages/English file+key if one exists (Keyed only; this mod
  ships no English DefInjected folder), otherwise the native English value read directly from the
  shipped Def in Mod/Defs (label/description/stage/rule fields resolved by dotted path against
  the Def's own XML, mirroring how the game itself falls back). Built by a script, not by hand,
  so the columns cannot drift from the mod.

  Original (source-language) text: Many Happy Returns is written from scratch in English, not
  ported from another language, so Original equals English throughout. Said once here, per
  TRANSLATIONS.md section 3, rather than on every row.

  logRulesInitiator.rulesStrings is a list of <li> grammar-rule strings, not a single value: each
  <li> becomes its own row, indexed.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node
    }
    return $entries
}

$script:stageSlugIndex = @{}  # "DefName" -> ordered dict of slug -> stage index, built as slugs are first seen
# Texts the session doubts on a read (terminology, tone, phrasing), keyed by their row key, with
# one line saying why. Filled by hand after reading the shipped French; not detected by pattern.
$script:manualDoubt = @{}

function Resolve-DefField($defsRoot, [string]$key) {
    # key looks like "DefName.field" or "DefName.stages.N.field" or "DefName.logRulesInitiator.rulesStrings",
    # or, as this mod ships it, "DefName.stages.<readable_slug>.field": RimWorld's list-index position is
    # what actually resolves the value, not the slug text, so the Nth distinct slug for a given DefName is
    # taken to mean stage index N-1, in the order it is first seen in the French file (which mirrors the
    # Def's own stage order).
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    if ($rest.Length -ge 2 -and $rest[0] -eq 'stages' -and $rest[1] -notmatch '^\d+$') {
        $slug = $rest[1]
        if (-not $script:stageSlugIndex.ContainsKey($defName)) { $script:stageSlugIndex[$defName] = [ordered]@{} }
        $map = $script:stageSlugIndex[$defName]
        if (-not $map.Contains($slug)) { $map[$slug] = $map.Count }
        $idx = $map[$slug]
        $rest = @('stages', [string]$idx) + $rest[2..($rest.Length - 1)]
    }
    if (-not $script:defCache.ContainsKey($defName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//*[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$defName] = $found
    }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    $cur = $node
    foreach ($p in $rest) {
        if ($null -eq $cur) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
        } else {
            $cur = $cur.$p
        }
    }
    return $cur
}

function Resolve-DefText($defsRoot, [string]$key) {
    $node = Resolve-DefField $defsRoot $key
    if ($null -eq $node) { return $null }
    if ($node -is [System.Xml.XmlElement]) { return $node.InnerText }
    return [string]$node
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$englishRoot = Join-Path $Root 'Mod/Languages/English'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by `_tools/Generate-FrenchReview.ps1` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** Many Happy Returns is written from scratch")
[void]$out.AppendLine("in English; it is not ported from another language, so there is no separate source-language")
[void]$out.AppendLine("text to show.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French | ? |")
    [void]$out.AppendLine("|---|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $frNode = $frEntries[$key]
        $liNodes = @($frNode.ChildNodes | Where-Object { $_.NodeType -eq 'Element' -and $_.Name -eq 'li' })

        $rows = @()
        if ($liNodes.Count -gt 0) {
            # A grammar-rule list (e.g. logRulesInitiator.rulesStrings): one row per <li>.
            $enNode = if ($enEntries.Contains($key)) { $enEntries[$key] } else { $null }
            $enLiNodes = if ($enNode) { @($enNode.ChildNodes | Where-Object { $_.NodeType -eq 'Element' -and $_.Name -eq 'li' }) } else { @() }
            $defNode = Resolve-DefField $defsRoot $key
            $defLiNodes = if ($defNode) { @($defNode.ChildNodes | Where-Object { $_.NodeType -eq 'Element' -and $_.Name -eq 'li' }) } else { @() }
            for ($i = 0; $i -lt $liNodes.Count; $i++) {
                $fr = $liNodes[$i].InnerText
                $en = if ($i -lt $enLiNodes.Count) { $enLiNodes[$i].InnerText }
                      elseif ($i -lt $defLiNodes.Count) { $defLiNodes[$i].InnerText }
                      else { $null }
                $rows += [pscustomobject]@{ Key = "$key[$i]"; En = $en; Fr = $fr }
            }
        } else {
            $fr = $frNode.InnerText
            $en = if ($enEntries.Contains($key)) { $enEntries[$key].InnerText } else { Resolve-DefText $defsRoot $key }
            $rows += [pscustomobject]@{ Key = $key; En = $en; Fr = $fr }
        }

        foreach ($row in $rows) {
            $en = $row.En
            if ($null -eq $en) { $en = '*(not found -- check by hand)*' }
            $orig = $en
            $doubt = ''
            if ($row.Fr -match '\?\?\?|TODO' ) { $doubt = 'placeholder text left in' }
            elseif ($row.Fr -match '\{PAWN_gender' -and $row.Fr -notmatch '\{PAWN_gender \? ') { $doubt = 'malformed gender switch' }
            if ($script:manualDoubt.ContainsKey($row.Key)) { $doubt = $script:manualDoubt[$row.Key] }
            $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
            $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
            $frCell = ($row.Fr -replace '\|', '\|') -replace "`n", ' '
            $keyCell = $row.Key -replace '\|', '\|'
            $doubtCell = $doubt -replace '\|', '\|'
            [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell | $doubtCell |")
        }
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
